### ISSUE TITLE
[2.0.1] 'No PostCSS Config found' (options.config)

### ISSUE THREAD

**Issue by Uriziel01** [postcss/postcss-loader#209]
After todays upgrade to postcss-loader 2.0.0 I'm getting `No PostCSS Config found` everywhere.

I'm using `weback.config.js` from [https://github.com/JeffreyWay/laravel-mix](https://github.com/JeffreyWay/laravel-mix) repository

My actual postCss options are:
``` js
    postCss: [
        require('autoprefixer')({
            browsers: ['Chrome >= 35',
                'Firefox >= 38',
                'Edge >= 12',
                'Explorer >= 10',
                'iOS >= 8',
                'Safari >= 8',
                'Android 2.3',
                'Android >= 4',
                'Opera >= 12'],
            cascade: true,
            add: true,
            remove: true
        })
    ]
```

**Comment by michael-ciniawsky** [comment]
Fixed in https://github.com/postcss/postcss-loader/commit/c4f006472a85d3bc36ae3f2f0e750291fd732b7b
Released in [v2.0.1](https://github.com/postcss/postcss-loader/releases/tag/v2.0.1)

😛

**Comment by Uriziel01** [comment]
Now I'm getting other type of error messages:
```js
Module build failed: TypeError: Cannot create property 'prev' on boolean 'false'
    at Promise.resolve.then.then (C:\Users\Uriziel\ponteus\wp-content\themes\ponteus\node_modules\postcss-loader\lib\index.js:125:47)
```

**Comment by michael-ciniawsky** [comment]
Did you update to v2.0.1? This should also be fixed also in v2.0.1 😛

**Comment by michael-ciniawsky** [comment]
You make me sweat here :D, mom I will investigate

**Comment by gtwilliams03** [comment]
I am getting the same error using the `font-awesome-webpack2` package:

```
ERROR in ./~/css-loader?sourceMap&-minimize!./~/postcss-loader/lib!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-sass/assets/stylesheets/_bootstrap.scss
Module build failed: TypeError: Cannot create property 'prev' on boolean 'false'
    at Promise.resolve.then.then (/Users/gtw/clearwater-public-web/node_modules/postcss-loader/lib/index.js:125:47)
 @ ./~/bootstrap-sass/assets/stylesheets/_bootstrap.scss 4:14-175 18:2-22:4 19:20-181
 @ ./src/layouts/CoreLayout/CoreLayout.js
 @ ./src/main.js
 @ multi font-awesome-webpack2 ./src/main.js webpack-hot-middleware/client?path=http://192.168.4.61:3000/__webpack_hmr
```

**Comment by iAdramelk** [comment]
Don't use starter kit, and tried to update to postcss-loader 2.0.1, still have `No PostCSS Config found` message. Have pretty big postcss config in few separate postcss.config.js files. What should I upload to help you find problem cause?

**Comment by mythz** [comment]
Had the [same issue](https://github.com/postcss/postcss-loader/issues/128#issuecomment-299910809) after installing the latest **postcss-loader**, so I reverted back to:

    "postcss-loader": "^1.3.3",

**Comment by Fardinak** [comment]
I'm also getting the original error (`2.0.1`).
Now, I'm not sure... am I allowed to NOT have a separate `postcss.config.js`? I don't have much to config; would rather keep it in my `webpack.config.js`.

**Comment by iAdramelk** [comment]
To clarify I do have `postcss.config.js` files, but not in the root category, they are in separate subfolders fro different entry points.

**Comment by michael-ciniawsky** [comment]
Please try the fix branch and provide feedback 😛 `npm i -D postcss/postcss-loader#fix`

@iAdramelk I'm especially interested in your setup :D

**Comment by jmbelloteau** [comment]
Same error here since I've upgrade:

`Module build failed: Error: No PostCSS Config found in: /websites/webpack`

Basicaly I was doing this:

```js

// ===========================
// LOADERS
// ===========================
  
module: {
    rules: [
      {
        test: /\.scss$/,
        use: ExtractCSSPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'postcss-loader', 'sass-loader']
        })
      },
      {
        test: /\.css$/,
        use: ExtractCSSPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'postcss-loader']
        })
      }
    ]
  },

// ===========================
// PLUGINS
// ===========================

  plugins: [

    // LOADER OPTIONS PLUGIN
    new webpack.LoaderOptionsPlugin({
      options: {
        postcss: [
          autoprefixer()
        ]
      }
    }),

    // EXTRACT CSS PLUGIN
    new ExtractCSSPlugin({
      filename: '[name].[contenthash:8].css',
      disable: config.debug
    })
  ]

}

```

If you want to see the complete config I just made a gist:

[webpack config gist](https://gist.github.com/jmbelloteau/576b4106eefeb658ec85618ed8d79b29)

**Comment by jmbelloteau** [comment]
I just try with the fix branch, that doesn't fix the bug. Got the same error message:

`Module build failed: Error: No PostCSS Config found`

**Comment by michael-ciniawsky** [comment]
@jmbelloteau With the fix branch `npm i -D postcss/postcss-loader#fix` && please don't use the `LoaderOptionsPlugin` anymore, it was only meant for webpack 2 beta to support loaders **incompatible** with webpack 2 config syntax, which isn't the case for `postcss-loader > 1.0.0`

**Comment by jmbelloteau** [comment]
@michael-ciniawsky sure I can make an other trial with your advice. If I don't use `LoaderOptionsPlugin` what is the recommended method to pass autoprefixer option to postcss?

**Comment by michael-ciniawsky** [comment]
```js
 {
    test: /\.css$/,
    use: ExtractCSSPlugin.extract({
          fallback: 'style-loader',
          use: [
             'css-loader', 
             { 
                loader: 'postcss-loader', 
                options: { 
                  plugins: [ require('autoprefixer')(...options) ] 
                }
             }
           ]
        })
}
```

**Comment by michael-ciniawsky** [comment]
```diff

-    // LOADER OPTIONS PLUGIN
-    new webpack.LoaderOptionsPlugin({
-      options: {
-       postcss: [
-          autoprefixer()
-        ]
-      }
-    }),
```

**Comment by iAdramelk** [comment]
@michael-ciniawsky still failing with #fix.

My file structure:

```
/
    webpack/
        admin/
            postcss.config.js
        application/
            postcss.config.js
        config/
            postcss/
                index.js
                media.js
                vars.js
```

postcss.config.js in webpack/application/

```
const config = require('../config/postcss');

module.exports = ctx => config(ctx, 'application');
```

webpack/config/postcss/index.js

```
/* eslint import/no-extraneous-dependencies: 0 */

const assets = require('postcss-assets');
const nested = require('postcss-nested');
const autoprefixer = require('autoprefixer');
const colorAlpha = require('postcss-color-alpha');
const flexbugs = require('postcss-flexbugs-fixes');
const simpleVars = require('postcss-simple-vars');
const customMedia = require('postcss-custom-media');
const inlineSVG = require('postcss-inline-svg');
const csso = require('postcss-csso');

const applicationMediaConfig = require('./media');
const {
  application: applicationVarsConfig,
  admin: adminVarsConfig,
  homepage: homepageVarsConfig,
} = require('./vars');

module.exports = function postcssConfig(ctx, pack) {
  const mediaPlugin = customMedia({ extensions: applicationMediaConfig });

  const applicationPlugins = [
    simpleVars({ variables: applicationVarsConfig }),
    mediaPlugin, flexbugs, autoprefixer, colorAlpha, nested, inlineSVG, assets,
  ];

  const landingPlugins = [
    simpleVars({ variables: applicationVarsConfig }),
    mediaPlugin, flexbugs, autoprefixer, colorAlpha, nested, inlineSVG, assets,
  ];

  const homepagePlugins = [
    simpleVars({ variables: homepageVarsConfig }),
    mediaPlugin, flexbugs, autoprefixer, colorAlpha, nested, inlineSVG, assets,
  ];

  const adminPlugins = [
    simpleVars({ variables: adminVarsConfig }), flexbugs,
    autoprefixer, colorAlpha, nested, assets,
  ];

  if (ctx.env === 'production') {
    adminPlugins.push(csso({ restructure: false }));
    applicationPlugins.push(csso({ restructure: false }));
    landingPlugins.push(csso({ restructure: false }));
    homepagePlugins.push(csso({ restructure: false }));
  }

  const packs = {
    admin: adminPlugins,
    application: applicationPlugins,
    landing: landingPlugins,
    homepage: homepagePlugins,
  };

  return {
    plugins: packs[pack],
  };
};
```

**Comment by michael-ciniawsky** [comment]
Config lookup starts from 'path.dirname(file)` and then walks the file tree upwards, if the config is in a separate folder, you need to set `options: { config: { path: 'path/to/postcss.config.js' }}` in `webpack.config.js` See the [README](https://github.com/postcss/postcss-loader#config-cascade)

**Comment by michael-ciniawsky** [comment]
You config setup is **insanely** complex tbh 😛

**Comment by jmbelloteau** [comment]
@michael-ciniawsky thank you so much It's working 😄

**Comment by iAdramelk** [comment]
@michael-ciniawsky not sure how to change it. Basically I have some css files in: `webpack/admin/**.pcss ` and `webpack/application/**.pcss`.

If I understand readme correctly, files in `webpack/admin/**.pcss` should see and use `webpack/admin/postcss.config.js` and files in `webpack/application/**.pcss` should see and use config from `webpack/application/postcss.config.js`. It worked this way in 1.3.3, but now it doesn't work for some reason.

What should I change?

**Comment by michael-ciniawsky** [comment]
@iAdramelk 

```
|– src
| |– admin
| | |– style.css
| | |– postcss.config.js
| |– application
| | |– style.css
| | |– postcss.config.js
|
|– webpack.config.js
|– package.json
```

Doesn't work ?

**Comment by michael-ciniawsky** [comment]
With `npm i -D postcss/postcss-loader#fix` in case you're currently on `v2.0.1` 😛

**Comment by iAdramelk** [comment]
In my case structure was:

```
|– webpack
| |– admin
| | |– components
| | | |– button
| | | | |– style.css
| | |– postcss.config.js
| |– application
| | |– components
| | | |– button
| | | | |– style.css
| | |– postcss.config.js
|– webpack.config.js
|– package.json
```

And in wasn't working with #fix branch.

**Comment by michael-ciniawsky** [comment]
@iAdramelk kk please post the relevant part of your `webpack.config.js`

**Comment by iAdramelk** [comment]
Here comes another insane config piece :)

```
const pcssLoader = {
  test: /.*\.pcss$/,
};

const pcssLoaders = [
  {
    loader: 'css-loader',
    query: {
      sourceMap: !isProduction,
      modules: true,
      localIdentName: isProduction ? '[hash:base64:4]' : '[name]__[local]___[hash:base64:3]',
      camelCase: true,
      minimize: false,
      importLoaders: 1,
    },
  },
  {
    loader: 'postcss-loader',
    query: {
      sourceMap: !isProduction
    }
  },
];

if (isProduction) {
  pcssLoader.loader = ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: pcssLoaders,
  });
} else {
  pcssLoader.use = ['style-loader', ...pcssLoaders];
}

config.module.rules.push(pcssLoader);
```

**Comment by michael-ciniawsky** [comment]
Which webpack version are you on atm?

**Comment by michael-ciniawsky** [comment]
**postcss.config.js**
```js
module.exports = ({ file, options, env }) => ({
  parser: file.extname === '.sss' ? 'sugarss' : false,
  plugins: {
    'postcss-nested': {},
    'cssnano': env === 'production' ? { safe: true } : false
  }
})
```

**webpack.config.js**
```
{
  test: /\.(sss|css)$/,
  use: env === 'development'
    ? [
      'style-loader',
      { loader: 'css-loader', options: { importLoaders: 1 } },
      {
        loader: 'postcss-loader',
        options: {
          sourceMap: true
        }
      }
    ]
    : ExtractTextPlugin.extract({
      fallback: 'style-loader',
      use: [
        { loader: 'css-loader', options: { importLoaders: 1 } },
        {
          loader: 'postcss-loader',
          options: {
            sourceMap: true
          }
        }
      ]
    })
},
```

```
NODE_ENV=production webpack 
NODE_ENV=development webpack-dev-server
```

Works on the `fix` branch 😊

**Comment by michael-ciniawsky** [comment]
[Hopefully 😛] fixed by https://github.com/postcss/postcss-loader/commit/e764761
Released in [`v2.0.2`](https://github.com/postcss/postcss-loader/releases/tag/v2.0.2)

Reopen if still regressions

@iAdramelk Please share link to a small repo I can debug, out of the gut I guess there is an error somewhere else aswell e.g `postcss-assets` + `webpack` didn't work well for me a while ago 😛

**Comment by rolele** [comment]
if there is no options passed to the postcss-loader I still get the error with 2.0.2
```
        {
          test: /\.scss$/,
          use: [{
              loader: 'style-loader'
            }, {
              loader: 'css-loader?modules&localIdentName=[hash:base64:4]&importLoaders=1&sourceMap&camelCase=true'
            }, {
              loader: 'postcss-loader'
            }, {
...
```

adding  
```
            }, {
              loader: 'postcss-loader',
              options: {
                sourceMap: true
              }
            }, {
```
solved the issue with 2.0.2

**Comment by mythz** [comment]
Same behavior as @rolele, v2.0.2 is still generates this error even when I have:

```js
new webpack.LoaderOptionsPlugin({
    options: {
        postcss: [
            require('precss'),
            require('autoprefixer')
        ]
    }
}),
```

This works though:

```js
    loader: ExtractTextPlugin.extract({
        fallback: 'raw-loader',
        use: [
            'css-loader' + (isProd ? '?minimize' : ''), 
            {loader: 'postcss-loader', options: { plugins: () => [ require('precss'), require('autoprefixer') ] }}, 
            'sass-loader'
        ]
    })
```

**Comment by mdudek** [comment]
I'm also using LoaderOptionsPlugin and it does not work with 2.0.2.

**Comment by michael-ciniawsky** [comment]
`LoaderOptionsPlugin` is **deprecated/unnecessary**, it was just for the webpack 2 beta phase to support loaders which didn't support the new webpack config format during that time, please **don't** use it anymore 😛 

`postcss-loader =< v1.0.0`
```
const query = loaderUtils.parseQuery(this.query) || this.options.postcss // <= the old webpack v1 config.postcss prop
```

`postcss-loader > v1.0.0` (`2.0.0`)
```
const options = loaderUtils.getOptions(this) // no config.postcss support since it's not needed anymore
```

**Comment by mythz** [comment]
What's the best way to maintain config in webpack.config so we can avoid polluting our projects with a more config files?

This works when you only need to define it for one rule:

            {loader: 'postcss-loader', options: { plugins: () => [ require('precss'), require('autoprefixer') ] }}, 

But it gets unwieldy when you have to apply it on multiple rules, what's the best way to define it once in a central location in webpack.config and have it applies to all postcss-loader rules?

**Comment by michael-ciniawsky** [comment]
If you need a dynamic config, 'polluting' your project would be the wisest descision

```js
{
   loader: 'postcss-loader'
   options: {
     config: { 
       ctx: { plugin2: {...options} } // ctx.options in postcss.config.js
    }
  }
}
```

**postcss.config.js**
```js
module.exports = ({ file, options, env }) => {
  parser: file.extname === '.sss' ? 'sugarss' : false
  plugins: {
    'plugin1': { root: file.dirname }
    'plugin2':  env === 'development' ? options.plugin2 : false
    'cssnano': env == 'production' { safe: true } : false
  }
}
```

and so on....

**webpack.config.js**
```
const env = process.env.NODE_ENV

function plugins (loader) {
   return [
      require('plugin')({ root: loader.resourcePath }),
      env === 'production' ? require('cssnano')({ safe: true }) : false
   ].filter(Boolean)
}

const config = {
  ...
  { 
     loader: 'postcss-loader',
     options: { plugins: plugins(loader) }
   }
  ...
}
```

That's all steps I resolved via `postcss-load-config` in a nutshell, sry but I won't give any futher support upon this use `postcss.config.js` or find your way 😛

**Comment by iAdramelk** [comment]
@michael-ciniawsky here, I created simplified repo without insane configs and inheritance. :) Just `postcss.config.js` with `autoprefixer` in folder and `webpack.config.js` in root directory.

Still failing in `2.0.2`:

https://github.com/iAdramelk/postcss-loader-bug

**Comment by kgrigas** [comment]
Removing postcss config from `LoaderOptionsPlugin` fixed the problem for me.

**Comment by michael-ciniawsky** [comment]
@iAdramelk Thx I will take a look as soon as possible :)

**Comment by michael-ciniawsky** [comment]
@iAdramelk Fixed && Released in [v2.0.4](https://github.com/postcss/postcss-loader/releases/tag/v2.0.4)

I was sloppy... 😛

**Comment by JPortegijs** [comment]
Is postcss.config.js actually required, can't I just specify the options directly in my webpack.config?

**Comment by michael-ciniawsky** [comment]
@JPortegijs Both are supported && loading hierarchy is`webpack.config.js` > `postcss.config.js`

**Comment by iAdramelk** [comment]
@michael-ciniawsky yep, no more error! Thank you very much.

**Comment by JPortegijs** [comment]
Everything good here, too! Thanks!

**Comment by th3fallen** [comment]
still getting the mentioned error on postcss-loader@2.0.5 using 

```
new webpack.LoaderOptionsPlugin({
      minimize: false,
      debug: true,
      options: {
        postcss: [autoprefixer({ browsers: ['last 2 versions'] })],
      },
    }),
```

**Comment by michael-ciniawsky** [comment]
I need to add this to the README... :stuck_out_tongue: 

@th3fallen `LoaderOptionsPlugin` doesn't work with `postcss-loader >= v2.0.0` anymore since it's deprecated to use for loader options, when the loader supports webpack 2 config syntax 

**webpack.config.js
```js
{
   test: /\.css$/,
   use: [ 
     ..., 
     ..., 
    { loader: 'postcss-loader', options: { plugins: [ require('autoprefixer')(options)) ] } }
  ]
}
```

**Comment by michael-ciniawsky** [comment]
```diff
new webpack.LoaderOptionsPlugin({
      minimize: false,
      debug: true,
-      options: {
-        postcss: [autoprefixer({ browsers: ['last 2 versions'] })],
-      },
    }),
```

**Comment by th3fallen** [comment]
@michael-ciniawsky thanks for the input but how would i manage that in this syntax? 
```
 {
        test: /\.(scss|css)$/,
        loader: ['style-loader', 'css-loader', 'postcss-loader', 'sass-loader'],
      },
```

**Comment by michael-ciniawsky** [comment]
@th3fallen 

**webpack.config.js
```js
// webpack 2 module.loaders => module.rules 
{
   test: /\.(scss|css)$/,
   use: [ // webpack 2 loader => use 
     'style-loader' 
    { loader: 'css-loader', options: { importLoaders: 2 }, // needed for webpack @import handling
    { loader: 'postcss-loader', options: { plugins: [ require('autoprefixer')(options)) ] } },
    { loader: 'sass-loader', options: { includePaths: [ /* path/to/@imports */ ]}
  ]
}
```

**Comment by th3fallen** [comment]
thanks @michael-ciniawsky that works for my dev env. but in my productions build that's formatted like this...

```
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
import getConfig from '../config';
const path = require('path');
const config = getConfig(process.env.NODE_ENV).config;

const publicPath = (config.PREFIX || '').replace(/\/$/, '') + path.join(process.env.PUBLIC_PATH || '/').replace(/^\./, '');

module.exports =  {
  plugins: [
    new webpack.LoaderOptionsPlugin({
      minimize: true,
      debug: false,
    }),
    new ExtractTextPlugin({
      filename: 'assets/css/[name]-[hash].css',
      allChunks: true,
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(scss|css)$/,
        loader: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            'style-loader',
            'css-loader',
            {
              loader: 'postcss-loader',
              options: { plugins: [require('autoprefixer')({ browsers: ['last 2 versions'] })] },
            },
            'sass-loader',
          ],
          publicPath,
        }),
      },
    ],
  },
};
```
im getting...

```
ERROR in ./~/css-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/app.scss
    Module build failed: TypeError: Cannot read property 'postcss' of null
        at Processor.normalize (/Users/clarktomlinson/Sites/When-I-Work/wheniwork-js/node_modules/postcss-loader/node_modules/postcss/lib/processor.es6:101:18)
        at new Processor (/Users/clarktomlinson/Sites/When-I-Work/wheniwork-js/node_modules/postcss-loader/node_modules/postcss/lib/processor.es6:35:29)
        at postcss (/Users/clarktomlinson/Sites/When-I-Work/wheniwork-js/node_modules/postcss-loader/node_modules/postcss/lib/postcss.es6:34:12)
        at Promise.resolve.then.then (/Users/clarktomlinson/Sites/When-I-Work/wheniwork-js/node_modules/postcss-loader/lib/index.js:137:12)
     @ ./~/style-loader!./~/css-loader!./~/postcss-loader/lib?{"plugins":[null]}!./~/sass-loader/lib/loader.js!./app/styles/app.scss 4:14-189
``` 
any ideas?

**Comment by evilebottnawi** [comment]
@th3fallen `{"plugins":[null]}` in error line, seems `require('autoprefixer')({ browsers: ['last 2 versions'] })` return `null`

**Comment by th3fallen** [comment]
so why would that exact same config work for my dev enviroment?

**Comment by th3fallen** [comment]
apparently adding `ident: 'postcss',` fixed it....

**Comment by michael-ciniawsky** [comment]
@th3fallen latest `postcss-loader` ? (`v2.0.5`)

and please remove `style-loader` from `ExtractTextPlugin.extract().use` you it should only get triggered via `fallback`

```diff
{
        test: /\.(scss|css)$/,
-       loader: ExtractTextPlugin.extract({
+       loader: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
-           'style-loader',
            'css-loader',
            {
              loader: 'postcss-loader',
              options: { plugins: [require('autoprefixer')({ browsers: ['last 2 versions'] })] },
            },
            'sass-loader',
          ],
          publicPath,
        }),
      },
```

**Comment by th3fallen** [comment]
@michael-ciniawsky yep, what you suggested works, not sure why not it does...

**Comment by michael-ciniawsky** [comment]
`style-loader` 'pitches'  code for `<style></style>` into your files, loading this madness can break `ETWP` and then the automatically generated `ident` might be missing, bc of a former error and your plugins don't get stringified etc etc... 😛 It works now and you get a separate 'autoprefixed' CSS file ?

**Comment by th3fallen** [comment]
no, i get 1 css file but that's what's expected from my build

**Comment by heisian** [comment]
Kept getting
```
ERROR in ./~/css-loader?{"modules":true,"importLoaders":3,"localIdentName":"[name]__[local]__[hash:base64:5]"}!./~/postcss-loader/lib!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"outputStyle":"expanded","sourceMap":true}!./main/src/accountPages/MyPolicies/Policy/policy.scss
Module build failed: Error: No PostCSS Config found in:
...
```

until I added:
```json
      {
        test: /\.scss$/,
        use: [{
          loader: 'style-loader'
        }, {
          loader: 'css-loader', options: {
            modules: true,
            importLoaders: 3,
            localIdentName: '[name]__[local]__[hash:base64:5]'
          }
        }, {
          loader: 'postcss-loader', options: {
+            plugins: [require('autoprefixer')]
          }
        }, {
          loader: 'resolve-url-loader'
        }, {
          loader: 'sass-loader', options: {
            outputStyle: 'expanded',
            sourceMap: true
          }
        }]
      },
```

**Comment by michael-ciniawsky** [comment]
@heisian That's the intended behaviour, either the setup (plugins && options) is specified in `webpack.config.js` or otherwise look for `postcss.config.js` and finally throw none are present, because without any setup, you parse the CSS to an AST for no reason and don't need `postcss-loader` (perf regression)

**Comment by heisian** [comment]
that config was in my `webpack.config.js` - not in to having a `postcss.config.js` file in 20+ folders, so `webpack.config.js` is preferred..

what is an AST? I apologize but this is about my 6th day of using Webpack in this manner.

Random tweaking has gotten me successful configs for both dev and production, however I could very well stand to learn more about what's actually going on here.

So.. why does adding the `autoprefixer` plugin get rid of the error? Isn't `autoprefixer` just a plugin for expanding out all the various permutations of CSS properties across browsers? Does `postcss-loader` by default require `autoprefixer` to function?

**Comment by michael-ciniawsky** [comment]
> that config was in my webpack.config.js - not a fan of having a postcss.config.js file in 20+ folders, so webpack.config.js is preferred..

You need **one**  `postcss.config.js` in the root (`./`), but it's enterily personal choice where to specified options :). More `postcss.configs.js` is only needed if you need different transforms (plugins) for certain files (Config Cascade)

```
CSS File {String} 
=> CSS Parser (e.g PostCSS) 
=> [Post]CSS AST {Object (JSON)} 
=> plugin1(plugin2(pluginN(ast))) 
=> PostCSS Stringifier 
=> CSS File {String} 
```

> What is an AST? 

AST => [Abstract Syntax Tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree) 

**File (Source)**
```css
.class {
   width: 25%;
}
```

**Interface (Syntax)**
```
<Selector> {
  <Declaration>: <Value>;
}
```

**AST (PostCSS)**
```js
Root {
  raws: { semicolon: false, after: '\n' },
  type: 'root',
  nodes: 
   [ 
    Rule {
       raws: [Object],
       type: 'rule',
       nodes: [Object],
       parent: [Circular],
       source: [Object],
       selector: '.class',
       lastEach: 2,
       indexes: {} 
    } 
  ],
  source: 
   { 
     input: 
     Input {
        css: '.class {\n  width: 25%;\n}\n',
        file: './src/index.css' 
     },
     start: { line: 1, column: 1 } 
  },
  lastEach: 2,
  indexes: {} 
}
```

> So.. why does adding the autoprefixer plugin get rid of the error?

In theory you could of course parse the CSS and stringify it back without any plugins (transforms), but this computation is unnecessary/useless then 😛

**Comment by evilebottnawi** [comment]
@michael-ciniawsky can we close conversation here? If someone want to write about bug or other stuff, let create new issue.

**Comment by michael-ciniawsky** [comment]
Yep, you can lock the thread anytime if you want 😛

**Comment by evilebottnawi** [comment]
If someone has problems, please create a new issue. Thanks!
